index:
   path: /
   controller: App\Controller\DefaultController::index

logout:
   path: /logout
   

# mairie:
#   ressource: routes/mairie/routes.yaml
#   prefix: mairie

# politicien:
#   ressource: routes/politicien/routes.yaml
#   prefix: politicien
